#!/usr/bin/env python3
import os
import sys
import subprocess
import time

# --- ANSI Colors for CLI Styling ---
LAVENDER = '\033[38;2;195;188;231m'
RED = '\033[1;31m'
GREEN = '\033[1;32m'
YELLOW = '\033[1;33m'
RESET = '\033[0m'
BOLD = '\033[1m'

def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

def print_banner():
    banner = f"""{LAVENDER}{BOLD}
███╗   ██╗ ██████╗ ██╗  ██╗███████╗ ██████╗██████╗ ██╗██████╗ ████████╗
████╗  ██║██╔═══██╗╚██╗██╔╝██╔════╝██╔════╝██╔══██╗██║██╔══██╗╚══██╔══╝
██╔██╗ ██║██║   ██║ ╚███╔╝ ███████╗██║     ██████╔╝██║██████╔╝   ██║   
██║╚██╗██║██║   ██║ ██╔██╗ ╚════██║██║     ██╔══██╗██║██╔═══╝    ██║   
██║ ╚████║╚██████╔╝██╔╝ ██╗███████║╚██████╗██║  ██║██║██║        ██║   
╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝        ╚═╝   
                                                                       
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀  {YELLOW}PERMANENT AIRGAP UTILITY{LAVENDER}  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀{RESET}
"""
    print(banner)

def run_cmd(command, ignore_errors=True):
    """Executes a shell command silently. Ignores errors by default."""
    try:
        subprocess.run(command, shell=True, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except subprocess.CalledProcessError:
        if not ignore_errors:
            print(f"{RED}[!] Command failed: {command}{RESET}")

def prompt_confirmation():
    print(f"{RED}{BOLD}WARNING: THIS ACTION IS DESTRUCTIVE AND PERMANENT.{RESET}")
    print(f"{YELLOW}This utility will systematically annihilate all networking capabilities:")
    print("  - Mask and disable all networking daemons.")
    print("  - Hard-block wireless and Bluetooth radios.")
    print("  - Blacklist kernel modules for networking hardware.")
    print(f"  - Install a persistent drop-all firewall.{RESET}\n")
    
    confirmation = input(f"Type {RED}'AIRGAP'{RESET} to proceed: ")
    if confirmation.strip() != "AIRGAP":
        print(f"\n{GREEN}Aborted. No changes were made to your system.{RESET}")
        sys.exit(0)
    print("\n")

def step_1_daemons():
    print(f"{LAVENDER}[*] Step 1: Neutralizing Networking Daemons...{RESET}")
    services = [
        "NetworkManager", "systemd-networkd", "systemd-resolved", 
        "wpa_supplicant", "iwd", "connman", "bluetooth", "dhcpcd", "networking"
    ]
    for svc in services:
        run_cmd(f"systemctl stop {svc}")
        run_cmd(f"systemctl disable {svc}")
        run_cmd(f"systemctl mask {svc}") # Masking symlinks it to /dev/null
    time.sleep(1)
    print(f"{GREEN}[+] Daemons stopped and masked.{RESET}")

def step_2_interfaces():
    print(f"{LAVENDER}[*] Step 2: Severing Active Interfaces & Radios...{RESET}")
    # Bring down all interfaces except loopback
    try:
        interfaces = subprocess.check_output("ls -1 /sys/class/net", shell=True, text=True).splitlines()
        for iface in interfaces:
            if iface != "lo":
                run_cmd(f"ip link set {iface} down")
    except Exception:
        pass
    
    # Block radios
    run_cmd("rfkill block all")
    time.sleep(1)
    print(f"{GREEN}[+] Interfaces brought down and radios hard-blocked.{RESET}")

def step_3_kernel_modules():
    print(f"{LAVENDER}[*] Step 3: Blacklisting Kernel Drivers...{RESET}")
    modules = [
        "iwlwifi", "e1000e", "igb", "r8169", "ath9k", "ath10k", "mt76", 
        "btusb", "bluetooth", "cfg80211", "mac80211"
    ]
    
    # Write absolute blacklist config
    blacklist_path = "/etc/modprobe.d/99-noxscript-airgap.conf"
    try:
        with open(blacklist_path, "w") as f:
            f.write("# Generated by NoxScript Permanent Airgap\n")
            for mod in modules:
                # /bin/false strictly prevents module load at boot
                f.write(f"install {mod} /bin/false\n") 
    except Exception as e:
        print(f"{RED}[!] Failed to write blacklist: {e}{RESET}")
    
    # Attempt runtime unload
    for mod in modules:
        run_cmd(f"modprobe -r {mod}")
        
    time.sleep(1)
    print(f"{GREEN}[+] Kernel networking drivers blacklisted and unloaded.{RESET}")

def step_4_firewall():
    print(f"{LAVENDER}[*] Step 4: Enforcing Kernel-Level Drop-All Firewall...{RESET}")
    # Apply immediate iptables drops
    run_cmd("iptables -P INPUT DROP")
    run_cmd("iptables -P FORWARD DROP")
    run_cmd("iptables -P OUTPUT DROP")
    run_cmd("iptables -A INPUT -i lo -j ACCEPT")
    run_cmd("iptables -A OUTPUT -o lo -j ACCEPT")
    
    # Create persistent systemd firewall service to guarantee drops on every boot
    service_content = """[Unit]
Description=NoxScript Persistent Airgap Firewall
Before=network.target

[Service]
Type=oneshot
ExecStart=/sbin/iptables -P INPUT DROP
ExecStart=/sbin/iptables -P FORWARD DROP
ExecStart=/sbin/iptables -P OUTPUT DROP
ExecStart=/sbin/iptables -I INPUT -i lo -j ACCEPT
ExecStart=/sbin/iptables -I OUTPUT -o lo -j ACCEPT
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
"""
    try:
        with open("/etc/systemd/system/noxscript-firewall.service", "w") as f:
            f.write(service_content)
        run_cmd("systemctl daemon-reload")
        run_cmd("systemctl enable --now noxscript-firewall.service")
    except Exception:
        pass

    time.sleep(1)
    print(f"{GREEN}[+] Global I/O traffic permanently dropped (except loopback).{RESET}")

def main():
    if os.geteuid() != 0:
        print(f"{RED}ERROR: NoxScript must be run as root. Try: sudo python3 noxscript.py{RESET}")
        sys.exit(1)

    clear_screen()
    print_banner()
    prompt_confirmation()
    
    step_1_daemons()
    step_2_interfaces()
    step_3_kernel_modules()
    step_4_firewall()
    
    print(f"\n{GREEN}{BOLD}SYSTEM SUCCESSFULLY AIRGAPPED.{RESET}")
    print(f"{YELLOW}Your machine is now cryptographically isolated from all physical and wireless networks.")
    print(f"Reboot to verify persistence.{RESET}\n")

if __name__ == "__main__":
    main()